---
kind: pipeline
name: default


steps:
  - name: linter
    image: snakepacker/python:all
    pull: always
    commands:
      - tox
    environment:
      TOXENV: lint

  - name: python 3.5
    image: snakepacker/python:all
    pull: always
    commands:
      - wait-for-port rabbitmq:5672 rabbitmq:5671
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py35
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      branch:
        - master

  - name: python 3.6
    image: snakepacker/python:all
    pull: always
    commands:
      - wait-for-port rabbitmq:5672 rabbitmq:5671
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      branch:
        - master

  - name: python 3.7
    image: snakepacker/python:all
    pull: always
    commands:
      - wait-for-port rabbitmq:5672 rabbitmq:5671
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      branch:
        - master

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USERNAME
      password:
        from_secret: SMTP_PASSWORD
      from:
        from_secret: SMTP_USERNAME
      when:
        status:
          - changed
          - failure

services:
  - name: rabbitmq
    image: mosquito/aiormq-rabbitmq:latest
    pull: always
    when:
      branch:
        - master
---
kind: signature
hmac: 9bd6a0156331c57ada322ef1f51b6c2614e75605bf2c881edb7f62d867ad1734

...
